version: 0.2

phases:
  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - aws s3 cp ./build/. s3://comet-frontend-dev-deployment --recursive
      
artifacts:
  files:
    - frontend/build/**