version: 0.2

phases:
  build:
    commands:
      - echo "$SHELL"
      - cd frontend
      - npm install
      - npm run build
      - |
        if [ "${BRANCH,,}" != prod ]
        then
          ENV="${BRANCH,,}-"
        else
          ENV=""
        fi
      - aws s3 cp ./build/. s3://${APPLICATION}-frontend-${ENV}deployment --recursive
      
artifacts:
  files:
    - frontend/build/**