version: 0.2

phases:

  install: 
    runtime-versions:
      nodejs: latest 
      python: 3.9
    commands:
      # initialize environment
      - |
        if [ "${BRANCH}" != prod ]
        then
          export ENV="-${BRANCH}"
        else
          export ENV=""
        fi
      # install frontend dependencies
      - |
        cd frontend
        npm install --force
        cd ..
      # start up Docker
      - |
        nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
        timeout 15 sh -c "until docker info; do echo .; sleep 1; done" 
      # log into ECR
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION |\
          docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # install Testing and Documentation Dependencies
      - |
        pip install behave==1.2.6 \
                    behave-html-formatter==0.9.8 \
                    requests==2.26.0 \
                    selenium==4.0.0 \
                    git-remote-codecommit==1.15.1
      # Download Sonar Scanner
      - |
        curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip \
            -o "sonar_scanner.zip"
        unzip sonar_scanner.zip > /dev/null 2>&1
        export PATH=$(pwd)/sonar-scanner-4.6.2.2472-linux/bin/:$PATH
  
  pre_build:
    commands:
      # TODO: unit tests!

      # lint source code
      # - |
      #   npx eslint --quiet \
      #     --no-error-on-unmatched-pattern ./src/** \
      #     --output-file ../docs/linting/index.html \
      #     --format html \
      #     || true
      #   aws s3 cp ../docs/linting/index.html \
      #           s3://${APPLICATION}-coverage${ENV}/linting/react/index.html
      
      # SonarQube static code analysis
      - |
        sonar-scanner \
          -Dsonar.projectKey=${APPLICATION}-frontend${ENV} \
          -Dsonar.host.url=https://$SONAR_URL \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.log.level=DEBUG \
          -Dsonar.sources=$(pwd)/frontend/src/ \
          -Dsonar.exclusions=**/*.json,**/*.css,**/*.test.js,**/*.svg \
          -Dsonar.sourceEncoding=UTF-8
      # -Dsonar.coverageReportPaths=path/to/coverage.xml
      # see: https://docs.sonarqube.org/latest/analysis/coverage/

  build:
    commands:
      - |
        bash -c '
          cp ./conf/nginx.proxy.conf ./conf/nginx.conf
          docker build -t ${APPLICATION}-frontend:${BRANCH^} .
          docker tag ${APPLICATION}-frontend:${BRANCH^} \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-frontend:${BRANCH^}
        '
  
  post_build:
    commands:
      # BDD Tests 
      - |
        bash -c '
          docker run --publish 8000:8000 \
                   --name ${APPLICATION}_backend \
                   --env COGNITO_USER_POOL=$POOL_ID \
                   --env COGNITO_AUDIENCE=$CLIENT_ID \
                   --env COGNITO_AWS_REGION=$AWS_DEFAULT_REGION \
                   --env APP_ENV=test \
                   --env APP_PORT=8000 \
                   --detach \
                   $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-backend:${BRANCH^}
          docker run --publish 8080:8080 \
                    --name ${APPLICATION}_frontend \
                    --env NGINX_PORT=8080 \
                    --env ROOT_DIR=/home/build \
                    --env PROXY_HOST=localhost \
                    --env PROXY_PORT=8000 \
                    --detach \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-frontend:${BRANCH^}
          git clone codecommit://${APPLICATION}-test-harness
          cd ${APPLICATION}-test-harness/python
          export FRONTEND_HOST_URL="http://localhost:8080"
          chmod +x ./configure && ./configure web
          behave -t "@Web" \
                --no-skipped \
                --summary \
                --outfile behave-report-frontend.html \
                --format behave_html_formatter:HTMLFormatter \
                  || true
          aws s3 cp ./behave-report-frontend.html \
                    s3://${APPLICATION}-coverage/test-coverage/bdd/behave-report-frontend.html
          cd ../..
        '
      # Generate documentation
      - |
        cd frontend
        npx typedoc
        aws s3 cp ../docs/package/. \
                s3://${APPLICATION}-coverage/frontend/ \
                --recursive
        

      # Invalidate Frontend & Coverage Distribution Cache
      - |
        aws cloudfront create-invalidation \
            --distribution-id $COVERAGE_DISTRIBUTION_ID \
            --paths "/*"

      # Push image to ECR 
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${APPLICATION}-frontend:${BRANCH^}

cache:
  path:
    - frontend/node_modules