version: 0.2

phases:
  install:
    runtime:
      nodejs: 16.x
    commands:
      # Download sonar scanner
      - curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -o "sonar_scanner.zip"
      - unzip sonar_scanner.zip
      - export PATH=$(pwd)/sonar-scanner-4.6.2.2472-linux/bin/:$PATH
  
  pre_build:
    commands:
      # TODO: Unit Tests
      #   generate coverage.xml and point SonarQube to it.
      # Sonar Qube
      - |
        sonar-scanner \
          -Dsonar.projectKey=innolab-frontend \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://$SONAR_URL:9000 \
          -Dsonar.login=$SONAR_TOKEN
          -Dsonar.log.level=DEBUG \
          -Dsonar.sources=$(pwd)/lambdas \
          -Dsonar.sourceEncoding=UTF-8 \
      # -Dsonar.coverageReportPaths=path/to/coverage.xml

      # see: https://docs.sonarqube.org/latest/analysis/coverage/

  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
      - |
        if [ "${BRANCH}" != prod ]
        then
          ENV="${BRANCH}-"
        else
          ENV=""
        fi
      - aws s3 cp ./build/. s3://${APPLICATION}-frontend-${ENV}deployment --recursive
      
artifacts:
  files:
    - frontend/build/**